quarkus.application.name=Bigote
quarkus.http.port=8080
smallrye.config.locations=file:///${config.path.fixed}/bigote.properties
ffmpeg.binary.location=C:/ProgramData/chocolatey/lib/ffmpeg/tools/ffmpeg/bin/ffmpeg.exe
yt-dlp.binary.location=
